version: '3.8'

services:
  # 管理后台 API
  admin-api:
    build:
      context: ./backend/admin-api
      dockerfile: Dockerfile
    ports:
      - "${ADMIN_API_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - API_TYPE=admin
    depends_on:
      - mongodb
    volumes:
      - ./backend/admin-api/logs:/app/logs
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]

  # 用户 API
  user-api:
    build:
      context: ./backend/user-api
      dockerfile: Dockerfile
    ports:
      - "${USER_API_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - API_TYPE=user
    depends_on:
      - mongodb
    volumes:
      - ./backend/user-api/logs:/app/logs
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]

  # 管理后台前端
  admin-ui:
    build:
      context: ./frontend/admin-ui
      dockerfile: Dockerfile
    ports:
      - "${ADMIN_UI_PORT}:80"
    depends_on:
      - admin-api
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]

  # 用户前端
  user-ui:
    build:
      context: ./frontend/user-ui
      dockerfile: Dockerfile
    ports:
      - "${USER_UI_PORT}:80"
    depends_on:
      - user-api
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]

  # MongoDB 数据库
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - admin-api
      - user-api
      - admin-ui
      - user-ui
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]

  # 交易策略引擎
  strategy-engine:
    build:
      context: ./backend/strategy-engine
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    depends_on:
      - mongodb
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]

volumes:
  mongodb_data:

networks:
  pandaspace-network:
    driver: bridge