version: '3.8'

services:
  user-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://admin:admin123@mongodb:27017/pandaspace?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - BINANCE_API_KEY=your_binance_api_key
      - BINANCE_API_SECRET=your_binance_api_secret
      - API_TYPE=user
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - pandaspace-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]

networks:
  pandaspace-network:
    external: true

volumes:
  mongodb_data: 